<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <UseSystemDrawing>true</UseSystemDrawing>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\WpfAiAutomation.Contracts\WpfAiAutomation.Contracts.csproj" />
    <PackageReference Include="FlaUI.Core" />
    <PackageReference Include="FlaUI.UIA3" />
  </ItemGroup>
</Project>
